


export const HOST_API = process.env.REACT_APP_HOST_API_KEY || "";
export const skyRidersData = {
    "surf": [
        {
            title: 'The surf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The surf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The surf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The surf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
    ],
    "kitesurf": [
        {
            title: 'The kitesurf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The kitesurf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The kitesurf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The kitesurf chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
    ],
    "ski": [
        {
            title: 'The ski chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The ski chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The ski chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
        {
            title: 'The ski chanel',
            description: `Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica`,
            location: 'Normandy',
            country: 'France',
            best_price: '1500',
            best_price_time: '9h 30min',
            low_price: '900',
            low_price_time: '15h 10min',
            fast_price: '1300',
            fast_price_time: '8h 15min',
        },
    ],
}